import { useEffect, useMemo, useState } from 'react'
import { Check, Loader, Package, Search } from 'lucide-react'
import CONFIG from '@/lib/config'

const EDGE_URL = `${CONFIG.SUPABASE_URL}/functions/v1/import-sourcing-share`

type Row = { receiving_code:string; invoice_code:string; supplier_name:string; product_id:string; product_name:string; product_image:string|null; variant_options:Record<string,string>|null; quantity:number }

export default function ImportReceivingLookupPage(){
  const code=useMemo(()=>decodeURIComponent(window.location.pathname.split('/').filter(Boolean).pop()||''),[])
  const [row,setRow]=useState<Row|null>(null)
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState('')
  useEffect(()=>{(async()=>{try{const res=await fetch(EDGE_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'receiving-lookup',receiving_code:code})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error||'Could not find this product.');setRow(data.row||null);if(!data.row)throw new Error('Product receiving code not found.')}catch(e){setError(e instanceof Error?e.message:'Could not find this product.')}finally{setLoading(false)}})()},[code])
  return <div className="min-h-screen bg-gray-50 flex items-center justify-center p-5"><div className="w-full max-w-lg bg-white rounded-3xl border border-gray-100 shadow-sm p-6">{loading?<div className="py-16 flex justify-center"><Loader className="w-7 h-7 animate-spin text-gray-400"/></div>:error?<div className="py-12 text-center"><Search className="w-9 h-9 mx-auto text-gray-300"/><h1 className="font-black text-lg mt-4">Product not found</h1><p className="text-sm text-gray-500 mt-2">{error}</p><p className="text-xs text-gray-400 mt-4">Code: {code}</p></div>:row?<div><div className="flex items-center gap-3 mb-6"><div className="w-11 h-11 rounded-xl bg-orange-500 flex items-center justify-center text-white"><Package className="w-5 h-5"/></div><div><p className="text-xs font-bold text-gray-500 uppercase tracking-wide">QAfrica Receiving</p><h1 className="font-black text-lg">Product identified</h1></div></div>{row.product_image&&<img src={row.product_image} alt="" className="w-full h-52 object-contain rounded-2xl bg-gray-50 mb-5"/>}<h2 className="text-xl font-black">{row.product_name}</h2>{row.variant_options&&Object.keys(row.variant_options).length>0&&<div className="mt-3 flex flex-wrap gap-2">{Object.entries(row.variant_options).map(([k,v])=><span key={k} className="px-2.5 py-1 rounded-lg bg-gray-100 text-xs font-bold">{k}: {v}</span>)}</div>}<div className="grid grid-cols-2 gap-3 mt-6"><div className="rounded-xl bg-gray-50 p-3"><p className="text-[10px] text-gray-500">Expected quantity</p><p className="text-xl font-black">{Number(row.quantity).toLocaleString()}</p></div><div className="rounded-xl bg-gray-50 p-3"><p className="text-[10px] text-gray-500">Supplier</p><p className="text-sm font-black mt-1">{row.supplier_name}</p></div></div><div className="mt-5 p-4 rounded-xl border border-green-100 bg-green-50 flex items-center gap-3"><Check className="w-5 h-5 text-green-600"/><div><p className="text-sm font-black text-green-800">Ready for inventory receiving</p><p className="text-xs text-green-700 mt-1">Invoice {row.invoice_code} · {row.receiving_code}</p></div></div></div>:null}</div></div>
}
