import { useEffect, useRef, useState } from 'react'
import { FileText, Loader, Upload, X, Plus, List, Send, Clock3, CheckCircle2, XCircle, WalletCards } from 'lucide-react'
import CONFIG from '@/lib/config'
import { getManagementToken } from './ManagementAuth'
import { useImportAdminPermissions } from '@/hooks/useImportAdminPermissions'

const LEGACY_EDGE_URL = CONFIG.SUPABASE_URL + '/functions/v1/import-admin-v2-expenses'
const REQUEST_EDGE_URL = CONFIG.SUPABASE_URL + '/functions/v1/import-expense-requests'
type Expense={id:string;title:string;description:string|null;amount:number;expense_date:string;receipt_name:string|null;status:'pending'|'paid'|'rejected';paid_at:string|null;created_at:string}
type PaymentRequest={id:string;request_number:string;request_type:'payment_request'|'reimbursement';title:string;purpose:string;amount:number;currency:string;expense_date:string;due_date:string|null;recipient_name:string|null;recipient_bank_name:string|null;recipient_account_name:string|null;recipient_account_number:string|null;recipient_phone:string|null;description:string|null;related_reference:string|null;status:'draft'|'pending_approval'|'approved'|'rejected'|'paid'|'cancelled';requested_by:string;approved_at:string|null;rejected_at:string|null;rejection_reason:string|null;paid_at:string|null;payment_reference:string|null;created_at:string}
const money=(n:number,currency='NGN')=>currency==='NGN'?'₦'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):currency+' '+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})
const REQUEST_PERMISSION='import.expenses.create'

export default function ManagementExpenses(){
 const token=getManagementToken()
 const {hasPermission,loading:permissionLoading}=useImportAdminPermissions(token)
 const [activeTab,setActiveTab]=useState<'add'|'view'|'requests'>('add')
 const [expenses,setExpenses]=useState<Expense[]>([])
 const [requests,setRequests]=useState<PaymentRequest[]>([])
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[amount,setAmount]=useState(''),[expenseDate,setExpenseDate]=useState(new Date().toISOString().slice(0,10)),[file,setFile]=useState<File|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const [requestsLoading,setRequestsLoading]=useState(false),[requestSaving,setRequestSaving]=useState(false),[requestError,setRequestError]=useState('')
 const [requestType,setRequestType]=useState<'payment_request'|'reimbursement'>('payment_request'),[requestTitle,setRequestTitle]=useState(''),[purpose,setPurpose]=useState(''),[requestAmount,setRequestAmount]=useState(''),[currency,setCurrency]=useState('NGN'),[dueDate,setDueDate]=useState('')
 const [recipientName,setRecipientName]=useState(''),[bankName,setBankName]=useState(''),[accountName,setAccountName]=useState(''),[accountNumber,setAccountNumber]=useState(''),[recipientPhone,setRecipientPhone]=useState(''),[requestDescription,setRequestDescription]=useState(''),[relatedReference,setRelatedReference]=useState('')
 const inputRef=useRef<HTMLInputElement>(null)
 const load=async()=>{if(!token){setError('Management session expired.');setLoading(false);return}try{const res=await fetch(LEGACY_EDGE_URL+'?action=list-mine',{headers:{'x-manager-token':token}});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not load expenses');setExpenses(data.expenses||[])}catch(e){setError(e instanceof Error?e.message:'Could not load expenses')}finally{setLoading(false)}}
 const loadRequests=async()=>{if(!token)return;setRequestsLoading(true);setRequestError('');try{const res=await fetch(REQUEST_EDGE_URL+'?action=list',{headers:{'x-manager-token':token}});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not load payment requests');setRequests(data.requests||[])}catch(e){setRequestError(e instanceof Error?e.message:'Could not load payment requests')}finally{setRequestsLoading(false)}}
 useEffect(()=>{void load()},[])
 useEffect(()=>{if(activeTab==='requests')void loadRequests()},[activeTab])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!token){setError('Management session expired.');return}if(!title.trim()||!amount||!file){setError('Please enter what the expense was for, the amount, and attach the receipt.');return}setSaving(true);try{const form=new FormData();form.set('title',title.trim());form.set('description',description.trim());form.set('amount',amount);form.set('expense_date',expenseDate);form.set('receipt',file);const res=await fetch(LEGACY_EDGE_URL+'?action=create',{method:'POST',headers:{'x-manager-token':token},body:form});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not submit expense');setTitle('');setDescription('');setAmount('');setFile(null);setExpenseDate(new Date().toISOString().slice(0,10));if(inputRef.current)inputRef.current.value='';await load()}catch(e){setError(e instanceof Error?e.message:'Could not submit expense')}finally{setSaving(false)}}
 const submitRequest=async(e:React.FormEvent)=>{e.preventDefault();setRequestError('');if(!token){setRequestError('Management session expired.');return}if(!hasPermission(REQUEST_PERMISSION)){setRequestError('You do not have permission to create payment requests.');return}if(!requestTitle.trim()||!purpose.trim()||!requestAmount){setRequestError('Title, purpose and amount are required.');return}if(requestType==='payment_request'&&(!recipientName.trim()||!bankName.trim()||!accountName.trim()||!accountNumber.trim())){setRequestError('Recipient name, bank name, account name and account number are required.');return}setRequestSaving(true);try{const res=await fetch(REQUEST_EDGE_URL+'?action=create',{method:'POST',headers:{'Content-Type':'application/json','x-manager-token':token},body:JSON.stringify({request_type:requestType,title:requestTitle.trim(),purpose:purpose.trim(),amount:Number(requestAmount),currency,expense_date:expenseDate,due_date:dueDate||null,recipient_name:recipientName.trim()||null,recipient_bank_name:bankName.trim()||null,recipient_account_name:accountName.trim()||null,recipient_account_number:accountNumber.trim()||null,recipient_phone:recipientPhone.trim()||null,description:requestDescription.trim()||null,related_reference:relatedReference.trim()||null})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not create payment request');setRequestTitle('');setPurpose('');setRequestAmount('');setDueDate('');setRecipientName('');setBankName('');setAccountName('');setAccountNumber('');setRecipientPhone('');setRequestDescription('');setRelatedReference('');setActiveTab('requests');await loadRequests()}catch(e){setRequestError(e instanceof Error?e.message:'Could not create payment request')}finally{setRequestSaving(false)}}
 const statusMeta=(status:PaymentRequest['status'])=>{if(status==='approved')return {label:'Approved',icon:CheckCircle2,cls:'bg-green-50 text-green-700'};if(status==='paid')return {label:'Paid',icon:WalletCards,cls:'bg-blue-50 text-blue-700'};if(status==='rejected')return {label:'Rejected',icon:XCircle,cls:'bg-red-50 text-red-700'};if(status==='pending_approval')return {label:'Pending approval',icon:Clock3,cls:'bg-amber-50 text-amber-700'};return {label:status.replace(/_/g,' '),icon:Clock3,cls:'bg-gray-100 text-gray-600'}}
 return <div className="max-w-6xl mx-auto space-y-5">
  <div><h2 className="text-xl font-bold text-gray-900">Expenses & Reimbursements</h2><p className="text-sm text-gray-500 mt-1">Your existing expenses remain here. Payment requests are managed alongside them.</p></div>
  <div className="bg-white rounded-2xl border border-gray-100 p-1.5 flex flex-wrap gap-1">
   <button type="button" onClick={()=>setActiveTab('add')} className={`flex-1 min-w-[140px] inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold transition-colors ${activeTab==='add'?'bg-gray-900 text-white':'text-gray-500 hover:bg-gray-50'}`}><Plus className="w-4 h-4"/>Add Expense</button>
   <button type="button" onClick={()=>setActiveTab('view')} className={`flex-1 min-w-[140px] inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold transition-colors ${activeTab==='view'?'bg-gray-900 text-white':'text-gray-500 hover:bg-gray-50'}`}><List className="w-4 h-4"/>View Expenses</button>
   {hasPermission(REQUEST_PERMISSION)&&<button type="button" onClick={()=>setActiveTab('requests')} className={`flex-1 min-w-[170px] inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold transition-colors ${activeTab==='requests'?'bg-gray-900 text-white':'text-gray-500 hover:bg-gray-50'}`}><Send className="w-4 h-4"/>Payment Requests</button>}
  </div>
  {activeTab==='add'&&<form onSubmit={submit} className="bg-white rounded-2xl border border-gray-100 p-5 space-y-4">
   <div className="grid sm:grid-cols-2 gap-4"><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">What was the expense for?</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Delivery to warehouse" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Amount (NGN)</span><input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label></div>
   <div className="grid sm:grid-cols-2 gap-4"><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Expense date</span><input type="date" value={expenseDate} onChange={e=>setExpenseDate(e.target.value)} className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Receipt</span><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} className="w-full text-xs"/></label></div>
   <label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Details (optional)</span><textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Add any useful details about the expense…" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm resize-none"/></label>
   {file&&<div className="flex items-center gap-2 text-xs text-gray-500 bg-gray-50 rounded-xl px-3 py-2"><FileText className="w-4 h-4"/><span className="truncate">{file.name}</span><button type="button" onClick={()=>{setFile(null);if(inputRef.current)inputRef.current.value=''}} className="ml-auto"><X className="w-4 h-4"/></button></div>}
   {error&&<div className="text-xs text-red-600 bg-red-50 border border-red-100 rounded-xl px-3 py-2">{error}</div>}
   <button disabled={saving} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gray-900 text-white text-sm font-semibold disabled:opacity-50">{saving?<Loader className="w-4 h-4 animate-spin"/>:<Upload className="w-4 h-4"/>}{saving?'Submitting…':'Submit expense'}</button>
  </form>}
  {activeTab==='view'&&<div className="bg-white rounded-2xl border border-gray-100 overflow-hidden"><div className="px-5 py-4 border-b border-gray-100"><p className="font-bold text-gray-900">My submissions</p></div>{loading?<div className="py-12 flex justify-center"><Loader className="w-5 h-5 animate-spin text-gray-300"/></div>:expenses.length===0?<div className="py-12 text-center text-sm text-gray-400">No expenses submitted yet.</div>:<div className="divide-y divide-gray-100">{expenses.map(x=><div key={x.id} className="px-5 py-4 flex flex-col sm:flex-row sm:items-center gap-3"><div className="flex-1 min-w-0"><p className="font-semibold text-sm text-gray-900">{x.title}</p><p className="text-xs text-gray-400 mt-1">{x.expense_date}{x.receipt_name?' · '+x.receipt_name:''}</p></div><div className="font-bold text-sm">{money(x.amount)}</div><span className={`px-2.5 py-1 rounded-full text-[10px] font-bold uppercase ${x.status==='paid'?'bg-green-50 text-green-700':x.status==='rejected'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{x.status}</span></div>)}</div>}</div>}
  {activeTab==='requests'&&<div className="space-y-4">
   <div className="bg-white rounded-2xl border border-gray-100 p-5"><div className="flex items-center justify-between gap-3 mb-4"><div><h3 className="font-bold text-gray-900">New Payment Request</h3><p className="text-xs text-gray-500 mt-1">Request money QAfrica needs to send or reimburse.</p></div><Send className="w-5 h-5 text-gray-400"/></div>
    <form onSubmit={submitRequest} className="space-y-4">
     <div className="grid sm:grid-cols-2 gap-4"><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Request type</span><select value={requestType} onChange={e=>setRequestType(e.target.value as 'payment_request'|'reimbursement')} className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"><option value="payment_request">Payment request</option><option value="reimbursement">Reimbursement</option></select></label><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Currency</span><select value={currency} onChange={e=>setCurrency(e.target.value)} className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"><option>NGN</option><option>USD</option><option>CNY</option></select></label></div>
     <div className="grid sm:grid-cols-2 gap-4"><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Request title</span><input required value={requestTitle} onChange={e=>setRequestTitle(e.target.value)} placeholder="e.g. Warehouse transportation" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Amount</span><input required type="number" min="0.01" step="0.01" value={requestAmount} onChange={e=>setRequestAmount(e.target.value)} placeholder="0.00" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label></div>
     <label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Purpose</span><input required value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="Why does QAfrica need to make this payment?" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label>
     <div className="grid sm:grid-cols-2 gap-4"><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Expense / request date</span><input type="date" value={expenseDate} onChange={e=>setExpenseDate(e.target.value)} className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Due date (optional)</span><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label></div>
     <div className="rounded-2xl bg-gray-50 border border-gray-100 p-4 space-y-4"><p className="text-xs font-bold text-gray-700">Payment recipient</p><div className="grid sm:grid-cols-2 gap-4"><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Recipient name</span><input value={recipientName} onChange={e=>setRecipientName(e.target.value)} placeholder="Full name" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Bank name</span><input value={bankName} onChange={e=>setBankName(e.target.value)} placeholder="Bank" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label></div><div className="grid sm:grid-cols-2 gap-4"><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Account name</span><input value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder="Account holder name" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Account number</span><input inputMode="numeric" value={accountNumber} onChange={e=>setAccountNumber(e.target.value)} placeholder="Account number" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label></div><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Phone (optional)</span><input value={recipientPhone} onChange={e=>setRecipientPhone(e.target.value)} placeholder="Recipient phone" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label></div>
     <div className="grid sm:grid-cols-2 gap-4"><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Related order / batch (optional)</span><input value={relatedReference} onChange={e=>setRelatedReference(e.target.value)} placeholder="e.g. Batch 24 or order code" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm"/></label><label><span className="block text-xs font-semibold text-gray-500 mb-1.5">Additional details (optional)</span><textarea rows={1} value={requestDescription} onChange={e=>setRequestDescription(e.target.value)} placeholder="Extra context…" className="w-full px-3 py-2.5 rounded-xl border border-gray-200 text-sm resize-none"/></label></div>
     {requestError&&<div className="text-xs text-red-600 bg-red-50 border border-red-100 rounded-xl px-3 py-2">{requestError}</div>}
     <button disabled={requestSaving||permissionLoading} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gray-900 text-white text-sm font-semibold disabled:opacity-50">{requestSaving?<Loader className="w-4 h-4 animate-spin"/>:<Send className="w-4 h-4"/>}{requestSaving?'Creating…':'Create payment request'}</button>
    </form>
   </div>
   <div className="bg-white rounded-2xl border border-gray-100 overflow-hidden"><div className="px-5 py-4 border-b border-gray-100 flex items-center justify-between gap-3"><div><p className="font-bold text-gray-900">Payment requests</p><p className="text-xs text-gray-500 mt-1">{requests.length} request{requests.length===1?'':'s'}</p></div><button type="button" onClick={()=>void loadRequests()} className="text-xs font-semibold text-gray-500 hover:text-gray-900">Refresh</button></div>{requestsLoading?<div className="py-12 flex justify-center"><Loader className="w-5 h-5 animate-spin text-gray-300"/></div>:requestError&&!requests.length?<div className="py-12 text-center text-sm text-red-500">{requestError}</div>:requests.length===0?<div className="py-12 text-center text-sm text-gray-400">No payment requests yet.</div>:<div className="divide-y divide-gray-100">{requests.map(r=>{const meta=statusMeta(r.status),Icon=meta.icon;return <div key={r.id} className="px-5 py-4 flex flex-col lg:flex-row lg:items-center gap-3"><div className="flex-1 min-w-0"><p className="font-semibold text-sm text-gray-900">{r.title}</p><p className="text-xs text-gray-400 mt-1">{r.request_number} · {new Date(r.created_at).toLocaleDateString()} · {r.recipient_name||'No recipient'}</p></div><div className="font-bold text-sm">{money(r.amount,r.currency)}</div><span className={`inline-flex items-center gap-1.5 self-start lg:self-auto px-2.5 py-1 rounded-full text-[10px] font-bold uppercase ${meta.cls}`}><Icon className="w-3 h-3"/>{meta.label}</span></div>})}</div>}</div>
  </div>}
 </div>
}
