import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Loader, PackageCheck, Search } from 'lucide-react';
import { toast } from 'sonner';
import CONFIG from '@/lib/config';

const BATCH_VIEW_URL = `${CONFIG.SUPABASE_URL}/functions/v1/import-batch-view`;
type Status = 'uncommitted' | 'committed' | 'purchased';
interface Line { id:string; order_id:string; product_id:string; customer_id:string; customer_name:string; order_code:string; product_name:string; product_image:string|null; source_url:string|null; quantity:number; status:Status; variant_options:Record<string,string>|null; }
async function call(action:string, body:Record<string,unknown>){const res=await fetch(`${BATCH_VIEW_URL}?action=${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));if(!res.ok||data.error)throw new Error(data.error||'Request failed');return data;}
export default function SourcingCommitmentPanel({token,batchKey}:{token:string;batchKey:string}){
 const [status,setStatus]=useState<Status>('uncommitted'); const [rows,setRows]=useState<Line[]>([]); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true); const [acting,setActing]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const r=await call('sourcing-commitments',{manager_token:token,batch_key:batchKey});setRows(r.rows??[])}catch(e){toast.error(e instanceof Error?e.message:'Could not load sourcing commitments')}finally{setLoading(false)}},[token,batchKey]);
 useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>r.status===status&&(!q||r.product_name.toLowerCase().includes(q)||r.customer_name.toLowerCase().includes(q)||r.order_code.toLowerCase().includes(q)))},[rows,status,search]);
 const counts=useMemo(()=>({uncommitted:rows.filter(r=>r.status==='uncommitted').length,committed:rows.filter(r=>r.status==='committed').length,purchased:rows.filter(r=>r.status==='purchased').length}),[rows]);
 const run=async(action:'commit-sourcing'|'mark-sourcing-bought',line:Line)=>{setActing(line.id);try{await call(action,{manager_token:token,batch_key:batchKey,allocation_id:line.id});toast.success(action==='commit-sourcing'?'Committed to sourcing':'Marked as bought');await load()}catch(e){toast.error(e instanceof Error?e.message:'Could not update sourcing status')}finally{setActing(null)}};
 return <div className="space-y-3">
  <div className="flex items-center gap-1 p-1 bg-gray-100 rounded-xl">{([['uncommitted','Uncommitted'],['committed','Committed'],['purchased','Bought']] as const).map(([key,label])=><button key={key} onClick={()=>setStatus(key)} className={`flex-1 px-3 py-2 rounded-lg text-[11px] font-bold ${status===key?'bg-white text-gray-900 shadow-sm':'text-gray-500'}`}>{label}<span className="ml-1 text-gray-400">{counts[key]}</span></button>)}</div>
  <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search product, customer or order…" className="w-full pl-9 pr-3 py-2.5 rounded-xl border border-gray-200 text-xs outline-none focus:border-gray-400"/></div>
  {loading?<div className="py-12 text-center"><Loader className="w-5 h-5 animate-spin text-gray-300 mx-auto"/></div>:filtered.length===0?<div className="py-10 text-center rounded-xl border border-dashed border-gray-200 text-xs text-gray-400">No {status==='purchased'?'bought':status} sourcing lines.</div>:<div className="space-y-2">{filtered.map(line=><div key={line.id} className="bg-white border border-gray-100 rounded-xl p-3 flex items-center gap-3">{line.product_image?<img src={line.product_image} alt="" className="w-12 h-12 rounded-lg object-cover bg-gray-50"/>:<div className="w-12 h-12 rounded-lg bg-gray-100 flex items-center justify-center"><PackageCheck className="w-5 h-5 text-gray-400"/></div>}<div className="min-w-0 flex-1"><div className="font-semibold text-xs text-gray-900 truncate">{line.product_name}</div><div className="text-[10px] text-gray-500 mt-0.5">{line.customer_name} · {line.order_code} · Qty {line.quantity}</div>{line.variant_options&&Object.keys(line.variant_options).length>0&&<div className="text-[10px] text-gray-400 mt-0.5">{Object.values(line.variant_options).join(', ')}</div>}</div>{status==='uncommitted'&&<button disabled={acting===line.id} onClick={()=>void run('commit-sourcing',line)} className="shrink-0 inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-gray-900 text-white text-[10px] font-bold disabled:opacity-50">{acting===line.id?<Loader className="w-3 h-3 animate-spin"/>:<CheckCircle2 className="w-3 h-3"/>}Commit</button>}{status==='committed'&&<button disabled={acting===line.id} onClick={()=>void run('mark-sourcing-bought',line)} className="shrink-0 inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-orange-500 text-white text-[10px] font-bold disabled:opacity-50">{acting===line.id?<Loader className="w-3 h-3 animate-spin"/>:<PackageCheck className="w-3 h-3"/>}Mark bought</button>}{status==='purchased'&&<span className="shrink-0 inline-flex items-center gap-1 text-[10px] font-bold text-green-600"><CheckCircle2 className="w-3 h-3"/>Bought</span>}</div>)}</div>}
 </div>
}