// src/pages/auth/Pricing/constants.ts

import { Star, Zap, Crown, Infinity as InfinityIcon } from 'lucide-react';
import CONFIG from '@/lib/config';

export const durations = [
  { value: 1,  label: '1 Month',  multiplier: 1,   discount: '0%'  },
  { value: 3,  label: '3 Months', multiplier: 2.7, discount: '10%' },
  { value: 6,  label: '6 Months', multiplier: 5,   discount: '17%' },
  { value: 12, label: '1 Year',   multiplier: 9,   discount: '25%' },
];

export const monthlyPlans = [
  {
    id: 'one_niche',
    name: 'Starter',
    icon: Star,
    description: 'Perfect for beginners',
    basePrice: CONFIG.PRICING?.SINGLE_NICHE || 5000,
    maxNiches: 1,
    features: [
      '1 Niche Selection',
      'Unlimited Products',
      'Basic Analytics',
      'Standard Themes',
      'Email Support',
      'Import Catalog (View Only)',
    ],
    cta: 'Get Started',
    popular: false,
  },
  {
    id: 'three_niches',
    name: 'Growth',
    icon: Zap,
    description: 'For expanding businesses',
    basePrice: CONFIG.PRICING?.THREE_NICHES || 10000,
    maxNiches: 3,
    features: [
      '3 Niche Selections',
      'Unlimited Products',
      'Advanced Analytics',
      'Premium Themes',
      'Priority Support',
      'Full Import Catalog Access',
      'Dropshipping Features',
    ],
    cta: 'Get Started',
    popular: true,
  },
  {
    id: 'unlimited',
    name: 'Enterprise',
    icon: Crown,
    description: 'For established brands',
    basePrice: CONFIG.PRICING?.UNLIMITED || 100000,
    maxNiches: Number.POSITIVE_INFINITY,
    features: [
      'Unlimited Niches',
      'Unlimited Products',
      'Full Analytics Suite',
      'All Themes + Custom',
      '24/7 Priority Support',
      'Import Catalog + Dropship',
      'Dedicated Account Manager',
      'API Access',
    ],
    cta: 'Contact Sales',
    popular: false,
  },
] as const;

export const lifetimePlans = [
  {
    id: 'one_niche',
    name: 'Starter Lifetime',
    icon: Star,
    description: 'One-time payment, lifetime access',
    price: 2000000,
    maxNiches: 1,
    features: [
      '1 Niche Selection - Forever',
      'Unlimited Products',
      'Basic Analytics',
      'Standard Themes',
      'Email Support',
      'No Monthly Fees Ever',
    ],
    cta: 'Buy Lifetime',
    popular: false,
    badge: 'Save 90%+',
  },
  {
    id: 'three_niches',
    name: 'Growth Lifetime',
    icon: Zap,
    description: 'Best value for serious sellers',
    price: 3800000,
    maxNiches: 3,
    features: [
      '3 Niche Selections - Forever',
      'Unlimited Products',
      'Advanced Analytics',
      'Premium Themes',
      'Priority Support',
      'Full Import Catalog',
      'Dropshipping Features',
      'No Monthly Fees Ever',
    ],
    cta: 'Buy Lifetime',
    popular: true,
    badge: 'Best Value',
  },
  {
    id: 'unlimited',
    name: 'Enterprise Lifetime',
    icon: InfinityIcon,
    description: 'Ultimate power for big brands',
    price: 10000000,
    maxNiches: Number.POSITIVE_INFINITY,
    features: [
      'Unlimited Niches - Forever',
      'Unlimited Products',
      'Full Analytics Suite',
      'All Themes + Custom',
      '24/7 Priority Support',
      'Import + Dropship',
      'Dedicated Manager',
      'API Access',
      'No Monthly Fees Ever',
    ],
    cta: 'Buy Lifetime',
    popular: false,
    badge: 'Ultimate',
  },
] as const;