import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Check, Info, Loader, Plus, Trash2, Upload, X } from 'lucide-react';
import { compressImage } from '@/lib/imageCompression';
import CONFIG from '@/lib/config';
import { getManagementToken } from './ManagementAuth';

const EDGE_URL = CONFIG.SUPABASE_URL + '/functions/v1/import-management';
const IMPORT_EDGE_URL = CONFIG.SUPABASE_URL + '/functions/v1/china-import';
const CATEGORY_EDGE_URL = CONFIG.SUPABASE_URL + '/functions/v1/category';
const COLORS = ['Black','White','Red','Blue','Green','Yellow','Grey','Pink','Purple','Orange','Brown','Beige'];
const SIZES = ['XS','S','M','L','XL','XXL','3XL','One Size','36','37','38','39','40','41','42','43','44','45','46'];
const input = 'w-full px-4 py-2.5 rounded-xl border border-gray-200 text-sm focus:border-gray-400 focus:ring-2 focus:ring-gray-200 outline-none bg-white';

type VariantGroup={id:string;name:string;options:string[];price_deltas?:Record<string,number>};
type Category={id:string;niche_id:string;name:string;sort_order:number;subcategories:{id:string;category_id:string;niche_id:string;name:string;sort_order:number;markup_percent:number}[]};
type Pricing={usdToNgn:number;cnyToUsd:number;seaRate:number;airRate:number;seaProductPct:number;seaCustomerPct:number;airCreditEnabled:boolean};
type Form={name:string;description:string;category:string;category_id:string;subcategory_id:string;original_price_usd:string;moq:string;source_url:string;ship_only:boolean;volume_cbm:string;weight_grams:string;units_sold:string;is_active:boolean};

const blankForm=():Form=>({name:'',description:'',category:'General',category_id:'',subcategory_id:'',original_price_usd:'',moq:'1',source_url:'',ship_only:false,volume_cbm:'',weight_grams:'',units_sold:'',is_active:true});
const round2=(n:number)=>Math.round(n*100)/100;

function calculate(priceUsd:number,markup:number,s:Pricing,volume:number,weight:number){
  const base=priceUsd*s.usdToNgn;
  const markupNgn=base*markup/100;
  const rawSea=Math.max(volume,0)*s.seaRate;
  const seaAllocation=rawSea*s.seaProductPct/100;
  const seaCustomer=rawSea*s.seaCustomerPct/100;
  const rawAir=Math.max(weight,0)*s.airRate;
  const airCustomer=Math.max(rawAir-(s.airCreditEnabled?seaAllocation:0),0);
  const ngn=base+markupNgn+seaAllocation;
  const usd=s.usdToNgn>0?ngn/s.usdToNgn:0;
  const cny=s.cnyToUsd>0?usd/s.cnyToUsd:0;
  return {base:round2(base),markupNgn:round2(markupNgn),productCost:round2(base+markupNgn),seaAllocation:round2(seaAllocation),seaCustomer:round2(seaCustomer),airCustomer:round2(airCustomer),ngn:round2(ngn),usd:round2(usd),cny:round2(cny)};
}

export default function ManagementProductAdd({productId:productIdProp}:{productId?:string}={}){
  const navigate=useNavigate();const {id:routeId}=useParams();const productId=productIdProp||routeId;const editing=Boolean(productId);
  const [form,setForm]=useState<Form>(blankForm);const [variants,setVariants]=useState<VariantGroup[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [pricing,setPricing]=useState<Pricing|null>(null);
  const [loading,setLoading]=useState(editing);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [customGroup,setCustomGroup]=useState('');const [drafts,setDrafts]=useState<Record<string,string>>({});
  const [expanded,setExpanded]=useState<Set<string>>(new Set());const [previews,setPreviews]=useState<string[]>([]);const [files,setFiles]=useState<(File|null)[]>([null,null,null]);
  const setField=<K extends keyof Form>(key:K,value:Form[K])=>setForm(p=>({...p,[key]:value}));

  useEffect(()=>{let cancelled=false;(async()=>{try{const [cr,sr]=await Promise.all([fetch(CATEGORY_EDGE_URL+'?action=list'),fetch(IMPORT_EDGE_URL+'?action=admin-pricing-settings')]);const cd=await cr.json().catch(()=>({}));const sd=await sr.json().catch(()=>({}));if(cancelled)return;setCategories(Array.isArray(cd.categories)?cd.categories:[]);const s=sd.settings;if(s)setPricing({usdToNgn:Number(s.usd_to_ngn),cnyToUsd:Number(s.cny_to_usd),seaRate:Number(s.sea_rate_ngn_per_cbm),airRate:Number(s.air_rate_ngn_per_gram??s.flight_rate_ngn_per_gram),seaProductPct:Number(s.sea_product_allocation_percent??s.sea_shipping_product_allocation_percent),seaCustomerPct:Number(s.sea_customer_percent??s.sea_shipping_customer_percent),airCreditEnabled:s.air_credit_enabled!==false});}catch{if(!cancelled)setError('Could not load categories and pricing settings.')}})();return()=>{cancelled=true}},[]);

  useEffect(()=>{if(!productId){setLoading(false);return}let cancelled=false;(async()=>{try{const token=getManagementToken();if(!token)throw new Error('Management session expired');const res=await fetch(EDGE_URL+'?action=admin-product',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({manager_token:token,id:productId})});const data=await res.json().catch(()=>({}));if(!res.ok||!data.product)throw new Error(data.error||'Could not load product');if(cancelled)return;const p=data.product;const amount=p.original_price_usd!=null?String(p.original_price_usd):p.price_cny_original!=null&&pricing?.cnyToUsd?String(Number(p.price_cny_original)*pricing.cnyToUsd):p.cost_ngn!=null&&pricing?.usdToNgn?String(Number(p.cost_ngn)/pricing.usdToNgn):'';const urls=Array.isArray(p.image_urls)&&p.image_urls.length?p.image_urls.slice(0,3):(p.image_url?[p.image_url]:[]);setForm({name:p.name||'',description:p.description||'',category:p.category||p.parent_category||'General',category_id:p.category_id||'',subcategory_id:p.subcategory_id||'',original_price_usd:amount,moq:String(p.moq??1),source_url:p.source_url||'',ship_only:p.ship_only===true,volume_cbm:p.volume_cbm==null?'':String(p.volume_cbm),weight_grams:p.weight_grams==null?'':String(p.weight_grams),units_sold:p.units_sold==null?'':String(p.units_sold),is_active:p.is_active!==false});setVariants(Array.isArray(p.variants)?p.variants.map((g:VariantGroup)=>({...g,id:g.id||crypto.randomUUID()})):[]);setPreviews(urls);setFiles([null,null,null]);}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Could not load product')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[productId,pricing?.cnyToUsd,pricing?.usdToNgn]);

  const category=useMemo(()=>categories.find(c=>c.id===form.category_id),[categories,form.category_id]);const subcategory=useMemo(()=>category?.subcategories.find(s=>s.id===form.subcategory_id),[category,form.subcategory_id]);
  const amount=Number(form.original_price_usd)||0;const volume=Number(form.volume_cbm)||0;const weight=Number(form.weight_grams)||0;const markup=Number(subcategory?.markup_percent??0);const preview=pricing?calculate(amount,markup,pricing,volume,weight):null;

  const togglePreset=(name:string,option:string)=>setVariants(prev=>{const group=prev.find(g=>g.name===name);if(!group)return[...prev,{id:crypto.randomUUID(),name,options:[option]}];const options=group.options.includes(option)?group.options.filter(x=>x!==option):[...group.options,option];return options.length?prev.map(g=>g.id===group.id?{...g,options}:g):prev.filter(g=>g.id!==group.id)});
  const addGroup=()=>{const n=customGroup.trim();if(!n||variants.some(g=>g.name.toLowerCase()===n.toLowerCase()))return;setVariants(v=>[...v,{id:crypto.randomUUID(),name:n,options:[]}]);setCustomGroup('')};
  const addOption=(id:string)=>{const n=(drafts[id]||'').trim();if(!n)return;setVariants(v=>v.map(g=>g.id===id&&!g.options.includes(n)?{...g,options:[...g.options,n]}:g));setDrafts(d=>({...d,[id]:''}))};
  const removeOption=(id:string,o:string)=>setVariants(v=>v.map(g=>g.id===id?{...g,options:g.options.filter(x=>x!==o)}:g).filter(g=>g.options.length));
  const removeGroup=(id:string)=>setVariants(v=>v.filter(g=>g.id!==id));
  const setDelta=(id:string,o:string,value:string)=>{const n=value.trim()===''?undefined:Number(value);setVariants(v=>v.map(g=>{if(g.id!==id)return g;const deltas={...(g.price_deltas||{})};if(n==null||Number.isNaN(n)||n===0)delete deltas[o];else deltas[o]=n;return {...g,price_deltas:Object.keys(deltas).length?deltas:undefined}}))};

  const addImage=async(e:React.ChangeEvent<HTMLInputElement>,slot:number)=>{const file=e.target.files?.[0];if(!file)return;try{const compressed=await compressImage(file,{maxWidth:800,maxHeight:800,targetSizeKb:100});setFiles(v=>{const n=[...v];n[slot]=compressed;return n});setPreviews(v=>{const n=[...v];n[slot]=URL.createObjectURL(compressed);return n})}catch{setError('Could not process that image. Please choose another image.')}e.target.value=''};
  const removeImage=(slot:number)=>{setPreviews(v=>{const n=[...v];n.splice(slot,1);return n});setFiles(v=>{const n=[...v];n.splice(slot,1);n.push(null);return n})};
  const upload=async(file:File)=>{const token=getManagementToken();if(!token)throw new Error('Management session expired');const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=()=>reject(new Error('Failed to read image'));r.readAsDataURL(file)});const res=await fetch(EDGE_URL+'?action=admin-product-upload-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({manager_token:token,image_base64:base64,extension:file.name.split('.').pop()||'jpg'})});const data=await res.json().catch(()=>({}));if(!res.ok||!data.url)throw new Error(data.error||'Image upload failed');return data.url as string};

  const save=async()=>{setError('');if(!form.name.trim())return setError('Product name is required.');if(!amount||amount<=0)return setError('Enter the original supplier price in USD.');if(!previews.length)return setError('Add at least one product photo.');if(!form.category_id||!form.subcategory_id)return setError('Select both a category and subcategory.');setSaving(true);try{const token=getManagementToken();if(!token)throw new Error('Management session expired');const urls:string[]=[];for(let i=0;i<3;i++){if(files[i])urls.push(await upload(files[i]!));else if(previews[i]&&!previews[i].startsWith('blob:'))urls.push(previews[i])}if(!urls.length)throw new Error('The product needs at least one uploaded image.');const clean=variants.filter(g=>g.name.trim()&&g.options.length).map(g=>({...g,name:g.name.trim(),options:g.options.map(o=>o.trim()).filter(Boolean)}));const p=preview||calculate(amount,markup,pricing||{usdToNgn:0,cnyToUsd:0,seaRate:0,airRate:0,seaProductPct:80,seaCustomerPct:20,airCreditEnabled:true},volume,weight);const body={manager_token:token,...(editing?{id:productId}:{}),name:form.name.trim(),description:form.description.trim(),category:subcategory?.name||form.category,parent_category:category?.name||form.category,category_id:form.category_id,subcategory_id:form.subcategory_id,image_url:urls[0],image_urls:urls,price_cny_original:pricing?.cnyToUsd?round2(amount/pricing.cnyToUsd):null,price_cny:p.cny,price_ngn:p.ngn,price_usd:p.usd,cost_ngn:p.base,price_input_currency:'usd',price_input_amount:round2(amount),original_price_usd:round2(amount),usd_to_ngn_rate:pricing?.usdToNgn?round2(pricing.usdToNgn):null,markup_percent:round2(markup),markup_amount_ngn:p.markupNgn,volume_cbm:volume>0?volume:null,weight_grams:weight>0?weight:null,sea_shipping_allocation_ngn:p.seaAllocation,sea_shipping_customer_ngn:p.seaCustomer,air_shipping_customer_ngn:p.airCustomer,sea_shipping_cost_ngn:p.seaCustomer,flight_shipping_cost_ngn:p.airCustomer,moq:Math.max(1,Number(form.moq)||1),units_sold:Math.max(0,Number(form.units_sold)||0),has_variants:clean.length>0,variants:clean,source_url:form.source_url.trim(),ship_only:form.ship_only,delivery_time:form.ship_only?'sea':'air',is_active:form.is_active};const action=editing?'admin-product-update':'admin-product-create';const res=await fetch(EDGE_URL+'?action='+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||(editing?'Could not update product':'Could not create product'));navigate('/management/products')}catch(e){setError(e instanceof Error?e.message:'Could not save product')}finally{setSaving(false)}};

  if(loading)return <div className="min-h-[50vh] flex items-center justify-center"><Loader className="w-5 h-5 text-orange-500 animate-spin"/></div>;
  const slots=Math.min(3,previews.length+1);

  return <div className="max-w-5xl space-y-4 pb-8">
    <div className="flex items-center gap-3"><button onClick={()=>navigate('/management/products')} className="p-2 rounded-lg hover:bg-gray-100"><ArrowLeft className="w-5 h-5"/></button><div><h1 className="font-bold text-gray-900">{editing?'Edit product':'Add product'}</h1><p className="text-xs text-gray-400">Same product template and pricing flow as Import Admin.</p></div></div>
    {error&&<div className="px-4 py-3 rounded-xl bg-red-50 text-red-600 text-xs">{error}</div>}

    <section className="bg-white rounded-2xl border border-gray-100 p-5 space-y-5">
      <h2 className="font-bold text-sm">Photos</h2>
      <div className="grid grid-cols-3 gap-2 max-w-sm">{Array.from({length:slots}).map((_,i)=>previews[i]?<div key={i} className="relative aspect-square rounded-xl overflow-hidden border border-gray-200 group"><img src={previews[i]} alt="" className="w-full h-full object-cover"/><button type="button" onClick={()=>removeImage(i)} className="absolute top-1.5 right-1.5 w-6 h-6 bg-white/90 rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100"><X className="w-3 h-3"/></button>{i===0&&<span className="absolute bottom-1.5 left-1.5 text-[9px] bg-gray-900/70 text-white px-1.5 py-0.5 rounded">Main</span>}</div>:<label key={i} className="cursor-pointer aspect-square rounded-xl border-2 border-dashed border-gray-200 flex flex-col items-center justify-center hover:border-gray-400"><Upload className="w-4 h-4 text-gray-300 mb-1"/><span className="text-[10px] text-gray-300">Add photo</span><input type="file" accept="image/*" className="hidden" onChange={e=>void addImage(e,i)}/></label>)}</div>
      <p className="text-[11px] text-gray-400">Up to 3 photos. The first is the main display image.</p>
      <label><span className="block text-[11px] font-semibold text-gray-400 uppercase tracking-widest mb-1.5">Product name</span><input value={form.name} onChange={e=>setField('name',e.target.value)} placeholder="e.g. Wireless Earbuds Pro" className={input}/></label>
      <label><span className="block text-[11px] font-semibold text-gray-400 uppercase tracking-widest mb-1.5">Description</span><textarea rows={2} value={form.description} onChange={e=>setField('description',e.target.value)} placeholder="Brief product description…" className={input+' resize-none'}/></label>
      <div className="grid sm:grid-cols-2 gap-4">
        <label><span className="block text-[11px] font-semibold text-gray-400 uppercase tracking-widest mb-1.5">Category</span><select value={form.category_id} onChange={e=>{const c=categories.find(x=>x.id===e.target.value);setForm(p=>({...p,category_id:e.target.value,subcategory_id:'',category:c?.name||'General'}))}} className={input}><option value="">Select category</option>{[...categories].sort((a,b)=>a.name.localeCompare(b.name)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
        <label><span className="block text-[11px] font-semibold text-gray-400 uppercase tracking-widest mb-1.5">Subcategory</span><select value={form.subcategory_id} disabled={!form.category_id} onChange={e=>setField('subcategory_id',e.target.value)} className={input+' disabled:bg-gray-100 disabled:text-gray-400'}><option value="">{form.category_id?'Select subcategory':'Select a category first'}</option>{[...(category?.subcategories||[])].sort((a,b)=>a.name.localeCompare(b.name)).map(s=><option key={s.id} value={s.id}>{s.name} ({Number(s.markup_percent||0).toFixed(2)}%)</option>)}</select></label>
      </div>
    </section>

    <section className="bg-white rounded-2xl border border-gray-100 p-5 space-y-5">
      <h2 className="font-bold text-sm">Pricing</h2>
      <div className="flex items-start gap-2 bg-blue-50 border border-blue-100 rounded-xl px-3 py-2.5"><Info className="w-3.5 h-3.5 text-blue-400 flex-shrink-0 mt-0.5"/><p className="text-[11px] text-blue-600">Enter the <strong>original supplier price in USD</strong>. The selected subcategory markup is applied automatically.</p></div>
      <input type="number" min={0} step="0.01" value={form.original_price_usd} onChange={e=>setField('original_price_usd',e.target.value)} placeholder="e.g. 10.00" className={input}/>
      {amount>0&&<div className="bg-gray-50 border border-gray-100 rounded-xl px-4 py-3 space-y-1.5"><div className="flex justify-between text-xs text-gray-500"><span>Original price</span><span>{'$'+amount.toFixed(2)}</span></div><div className="flex justify-between text-xs text-gray-500"><span>USD → NGN rate</span><span>{pricing?'₦'+pricing.usdToNgn.toLocaleString():'Loading…'}</span></div><div className="flex justify-between text-xs text-gray-500"><span>Base cost</span><span>{preview?'₦'+Math.round(preview.base).toLocaleString():'—'}</span></div><div className="flex justify-between text-xs text-gray-500"><span>Markup ({markup.toFixed(2)}%)</span><span className="text-orange-500">₦{preview?Math.round(preview.markupNgn).toLocaleString():'—'}</span></div><div className="h-px bg-gray-100"/><div className="flex justify-between text-xs font-bold text-gray-800"><span>Product cost before shipping</span><span>{preview?'₦'+Math.round(preview.productCost).toLocaleString():'—'}</span></div></div>}
      <label><span className="block text-[11px] font-semibold text-gray-400 uppercase tracking-widest mb-1.5">Minimum order quantity</span><input type="number" min={1} value={form.moq} onChange={e=>setField('moq',e.target.value)} className={input}/></label>
    </section>

    <section className="bg-white rounded-2xl border border-gray-100 p-5 space-y-5">
      <h2 className="font-bold text-sm">Sourcing & shipping</h2>
      <label><span className="block text-[11px] font-semibold text-gray-400 uppercase tracking-widest mb-1.5">1688 product link <span className="font-normal text-gray-400">(optional)</span></span><input type="url" value={form.source_url} onChange={e=>setField('source_url',e.target.value)} placeholder="https://detail.1688.com/offer/..." className={input}/><span className="block text-[11px] text-gray-400 mt-1">Only management staff see this supplier link.</span></label>
      <label className="flex items-start gap-3 px-4 py-3 rounded-xl border border-gray-200 cursor-pointer"><input type="checkbox" checked={form.ship_only} onChange={e=>setField('ship_only',e.target.checked)} className="mt-0.5 w-4 h-4 accent-orange-500"/><span><span className="block text-sm font-semibold text-gray-900">Sea freight only</span><span className="block text-[11px] text-gray-400">Customers cannot pick air for this product.</span></span></label>
      <div className="grid sm:grid-cols-2 gap-4"><label><span className="block text-[11px] font-semibold text-gray-400 uppercase tracking-widest mb-1.5">Volume for sea freight (CBM)</span><input type="number" min={0} step="0.001" value={form.volume_cbm} onChange={e=>setField('volume_cbm',e.target.value)} placeholder="e.g. 0.05" className={input}/></label><label><span className="block text-[11px] font-semibold text-gray-400 uppercase tracking-widest mb-1.5">Weight for flight (grams)</span><input type="number" min={0} value={form.weight_grams} onChange={e=>setField('weight_grams',e.target.value)} placeholder="e.g. 350" className={input}/></label></div>
      {preview&&(volume>0||weight>0)&&<div className="bg-gray-50 border border-gray-100 rounded-xl px-4 py-3 space-y-1.5">{volume>0&&<><div className="flex justify-between text-xs text-gray-500"><span>Raw sea freight</span><span>₦{Math.round(volume*(pricing?.seaRate||0)).toLocaleString()}</span></div><div className="flex justify-between text-xs text-gray-500"><span>Added to product ({(pricing?.seaProductPct||0).toFixed(2)}%)</span><span>₦{Math.round(preview.seaAllocation).toLocaleString()}</span></div><div className="flex justify-between text-xs text-gray-500"><span>Customer sea fee ({(pricing?.seaCustomerPct||0).toFixed(2)}%)</span><span>₦{Math.round(preview.seaCustomer).toLocaleString()}</span></div></>}{weight>0&&<><div className="flex justify-between text-xs text-gray-500"><span>Raw air freight</span><span>₦{Math.round(weight*(pricing?.airRate||0)).toLocaleString()}</span></div>{pricing?.airCreditEnabled&&<div className="flex justify-between text-xs text-gray-500"><span>Sea allocation credit</span><span className="text-emerald-600">−₦{Math.round(Math.min(preview.seaAllocation,weight*(pricing?.airRate||0))).toLocaleString()}</span></div>}<div className="flex justify-between text-xs font-bold text-gray-800"><span>Customer air fee</span><span>₦{Math.round(preview.airCustomer).toLocaleString()}</span></div></>}<div className="h-px bg-gray-100"/><div className="flex justify-between text-xs font-bold text-gray-800"><span>Product price incl. sea allocation</span><span>₦{Math.round(preview.ngn).toLocaleString()}</span></div></div>}
    </section>

    <section className="bg-white rounded-2xl border border-gray-100 p-5 space-y-4"><h2 className="font-bold text-sm">Sold count</h2><input type="number" min={0} value={form.units_sold} onChange={e=>setField('units_sold',e.target.value)} placeholder="0" className={input}/><p className="text-[11px] text-gray-400">Shown to customers as “X sold”.</p></section>

    <section className="bg-white rounded-2xl border border-gray-100 p-5 space-y-4">
      <h2 className="font-bold text-sm">Variants</h2>
      <div><p className="text-[11px] font-semibold text-gray-500 mb-1.5">Colors</p><div className="flex flex-wrap gap-1.5">{COLORS.map(o=>{const active=variants.find(g=>g.name==='Color')?.options.includes(o);return <button key={o} type="button" onClick={()=>togglePreset('Color',o)} className={'px-2.5 py-1 rounded-lg text-[11px] font-semibold border '+(active?'bg-gray-900 text-white border-gray-900':'bg-white text-gray-500 border-gray-200 hover:border-gray-400')}>{o}</button>})}</div></div>
      <div><p className="text-[11px] font-semibold text-gray-500 mb-1.5">Sizes</p><div className="flex flex-wrap gap-1.5">{SIZES.map(o=>{const active=variants.find(g=>g.name==='Size')?.options.includes(o);return <button key={o} type="button" onClick={()=>togglePreset('Size',o)} className={'px-2.5 py-1 rounded-lg text-[11px] font-semibold border '+(active?'bg-gray-900 text-white border-gray-900':'bg-white text-gray-500 border-gray-200 hover:border-gray-400')}>{o}</button>})}</div></div>
      {variants.filter(g=>g.name!=='Color'&&g.name!=='Size').map(g=>{const key='chips:'+g.id;const open=expanded.has(key);const opts=g.options.length>10&&!open?g.options.slice(0,10):g.options;return <div key={g.id} className="bg-white border border-gray-100 rounded-xl p-3"><div className="flex items-center justify-between mb-2"><p className="text-[11px] font-semibold text-gray-700">{g.name} <span className="text-gray-400">({g.options.length})</span></p><button type="button" onClick={()=>removeGroup(g.id)} className="text-gray-300 hover:text-red-400"><Trash2 className="w-3 h-3"/></button></div><div className="flex flex-wrap gap-1.5 mb-2">{opts.map(o=><span key={o} className="flex items-center gap-1 px-2 py-1 rounded-lg text-[11px] font-medium bg-gray-100 text-gray-600">{o}<button type="button" onClick={()=>removeOption(g.id,o)} className="text-gray-400"><X className="w-2.5 h-2.5"/></button></span>)}{g.options.length>10&&<button type="button" onClick={()=>setExpanded(p=>{const n=new Set(p);n.has(key)?n.delete(key):n.add(key);return n})} className="px-2 py-1 rounded-lg text-[11px] font-semibold border border-dashed border-gray-300 text-gray-500">{open?'Show less':'+'+(g.options.length-10)+' more'}</button>}</div><div className="flex gap-1.5"><input value={drafts[g.id]||''} onChange={e=>setDrafts(d=>({...d,[g.id]:e.target.value}))} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addOption(g.id)}}} placeholder="Add an option…" className="flex-1 px-3 py-1.5 rounded-lg border border-gray-200 text-xs"/><button type="button" onClick={()=>addOption(g.id)} className="px-2.5 py-1.5 bg-gray-100 rounded-lg"><Plus className="w-3 h-3"/></button></div></div>})}
      {variants.length>0&&(()=>{const rows=variants.flatMap(g=>g.options.map(o=>({g,o})));const open=expanded.has('price');const shown=rows.length>10&&!open?rows.slice(0,10):rows;return <div className="bg-white border border-gray-100 rounded-xl p-3"><p className="text-[11px] font-semibold text-gray-700">Price adjustments (optional)</p><p className="text-[10px] text-gray-400 mb-2.5">NGN adjustment for variants that cost more than the base product.</p><div className="space-y-2">{shown.map(({g,o})=><div key={g.id+o} className="flex items-center gap-2"><span className="text-[11px] text-gray-500 flex-1 truncate">{g.name}: <b className="text-gray-700">{o}</b></span><span className="text-[11px] text-gray-400">₦</span><input type="number" value={g.price_deltas?.[o]??''} onChange={e=>setDelta(g.id,o,e.target.value)} placeholder="0" className="w-24 px-2 py-1 rounded-lg border border-gray-200 text-xs text-right"/></div>)}</div>{rows.length>10&&<button type="button" onClick={()=>setExpanded(p=>{const n=new Set(p);n.has('price')?n.delete('price'):n.add('price');return n})} className="mt-2.5 w-full text-center py-1.5 rounded-lg text-[11px] font-semibold border border-dashed border-gray-300 text-gray-500">{open?'Show less':'Show all '+rows.length+' options'}</button>}</div>})()}
      <div className="flex gap-1.5"><input value={customGroup} onChange={e=>setCustomGroup(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addGroup()}}} placeholder="Custom variant name (e.g. Material)" className="flex-1 px-3 py-2 rounded-xl border border-gray-200 text-xs"/><button type="button" onClick={addGroup} className="px-3 py-2 bg-gray-100 rounded-xl text-gray-600 text-xs font-semibold flex items-center gap-1"><Plus className="w-3 h-3"/> Add</button></div>
    </section>

    <section className="bg-white rounded-2xl border border-gray-100 p-5 space-y-4"><h2 className="font-bold text-sm">Listing status</h2><label className="flex items-start gap-3 px-4 py-3 rounded-xl border border-gray-200 cursor-pointer"><input type="checkbox" checked={form.is_active} onChange={e=>setField('is_active',e.target.checked)} className="mt-0.5 w-4 h-4 accent-orange-500"/><span><span className="block text-sm font-semibold text-gray-900">Active</span><span className="block text-[11px] text-gray-400">Keep the product active in the catalogue.</span></span></label></section>

    <div className="flex justify-end gap-2"><button type="button" onClick={()=>navigate('/management/products')} className="px-4 py-2.5 rounded-xl border border-gray-200 text-xs font-semibold">Cancel</button><button type="button" onClick={()=>void save()} disabled={saving} className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gray-900 text-white text-xs font-bold disabled:opacity-60">{saving?<Loader className="w-4 h-4 animate-spin"/>:<Check className="w-4 h-4"/>}{editing?'Save changes':'Add product'}</button></div>
  </div>;
}
