-- Legacy storefront eligibility policy only.
-- This migration is NOT compatible with the active inventory-backed Supabase project
-- (firhntbbeclmhixivtic), which has no public.import_catalog table and whose products
-- table has no store_id, owner_id, stock_quantity, is_out_of_stock, or is_importable.
-- DO NOT apply this migration to the active QAfrica production database.
-- It must only be used after confirming a separate deployment of the legacy storefront schema.
