-- Import AI support tickets: structured support requests that can outlive a WhatsApp conversation.
create table if not exists public.import_support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity unique,
  customer_id uuid references public.customers(id) on delete set null,
  conversation_id uuid references public.import_ai_whatsapp_conversations(id) on delete set null,
  order_id uuid references public.china_import_orders(id) on delete set null,
  order_code text,
  category text not null default 'general',
  subject text not null,
  description text,
  status text not null default 'open' check (status in ('open','in_progress','waiting_customer','resolved','closed')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  assigned_agent_id uuid,
  resolution_notes text,
  created_by text not null default 'ai',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  closed_at timestamptz
);

create index if not exists import_support_tickets_status_idx on public.import_support_tickets(status);
create index if not exists import_support_tickets_customer_idx on public.import_support_tickets(customer_id);
create index if not exists import_support_tickets_conversation_idx on public.import_support_tickets(conversation_id);
create index if not exists import_support_tickets_order_idx on public.import_support_tickets(order_code);
create index if not exists import_support_tickets_updated_idx on public.import_support_tickets(updated_at desc);

alter table public.import_support_tickets enable row level security;

-- Admin access is intentionally performed through the import-support-tickets Edge Function
-- using the existing import_admin_sessions/role permission model.

after? 
